#!/bin/sh
make
if [ -f cook ]; then
	OBD=OBData.txt
	if [ -f ${OBD} ]; then
		echo "Renaming ${OBD} to ${OBD}.old"
		mv ${OBD} ${OBD}.old
		fi

printf "#
# OpenBoardData - OBData.txt
#
# DO NOT EDIT THIS FILE - it is automatically generated
#
# If you want to ammend or add a value, do so with the individual
# board file that is relevant.  This OBData.txt file will be
# generated using the build script.
#
#
" > ${OBD}


	for x in `find boards -name \*.txt`; do
		printf "Cooking ${x}..."
		./cook ${x} >> ${OBD}
		printf "done.\n"
		done

	echo "Finished."

	fi
